// DETERMINISTIC codegen from a Plan into the studio (never an LLM): the segmented/"worlds" template generalized from
// studio/src/mkv + studio/scripts/mkv. Writes src/<slug>/**, scripts/<slug>/** and the <mvo:…> regions of src/Root.tsx.
import {existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import type {Plan} from '../types.ts';
import {grid} from './plan.ts';
import {node, tail} from './exec.ts';
import {renderStills, typecheck} from './gates.ts';

const TEMPLATES = fileURLToPath(new URL('../../templates/segmented/', import.meta.url));
const MARK = 'GENERATED by motion-orchestrator';

export const pascal = (slug: string) => slug.split('-').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('');

// Where a video lives in the studio (paths relative to the studio root, '/' separators) + its composition ids.
export const layout = (slug: string) => ({
  src: `src/${slug}`,
  scripts: `scripts/${slug}`,
  public: `public/${slug}`,
  out: `out/${slug}`,
  reelId: pascal(slug),
  segCompId: `${pascal(slug)}Seg`,
});

// ── fonts: @remotion/google-fonts module + the normal-style weights it ships (Inter if the family is unknown) ──
function font(studioRoot: string, family: string): {mod: string; weights: string[]} | null {
  const mod = family.replace(/[^A-Za-z0-9]/g, '');
  const file = path.join(studioRoot, 'node_modules/@remotion/google-fonts/dist/esm', `${mod}.mjs`);
  if (!mod || !existsSync(file)) return null;
  const src = readFileSync(file, 'utf8');
  const normal = /\n {4}normal: \{([\s\S]*?)\n {4}\}/.exec(src.slice(src.indexOf('var getInfo')))?.[1];
  if (!normal || !/\blatin:/.test(normal)) return null;
  const all = [...normal.matchAll(/\n {6}"(\d+)": \{/g)].map((m) => m[1]);
  const pick = all.filter((w) => Number(w) >= 400);
  return all.length ? {mod, weights: pick.length ? pick : all} : null;
}

function brandFonts(plan: Plan, studioRoot: string, notes: string[]) {
  const imports: string[] = [];
  const defs: string[] = [];
  const seen = new Map<string, string>(); // module → const name
  const load = (role: string, family: string | undefined, fallbackConst?: string) => {
    if (!family) return defs.push(`export const ${role} = ${fallbackConst};`);
    let f = font(studioRoot, family);
    if (!f) {
      notes.push(`font "${family}" (${role}) is not in @remotion/google-fonts: using Inter`);
      f = font(studioRoot, 'Inter')!;
    }
    let local = seen.get(f.mod);
    if (!local) {
      local = `load${f.mod}`;
      seen.set(f.mod, local);
      imports.push(`import {loadFont as ${local}} from '@remotion/google-fonts/${f.mod}';`);
      defs.push(`const ${local}Family = ${local}('normal', {weights: ${JSON.stringify(f.weights)}, subsets: ['latin']}).fontFamily;`);
    }
    defs.push(`export const ${role} = ${local}Family;`);
  };
  load('FONT', plan.brand.fonts.display);
  load('BODY', plan.brand.fonts.body, 'FONT');
  load('MONO', plan.brand.fonts.mono, "'monospace'");
  return {imports: imports.join('\n'), defs: defs.join('\n')};
}

// ── template rendering ──
const fill = (text: string, vars: Record<string, string | number>) => text.replace(/__([A-Z][A-Z_]*?)__/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
const comment = (s: string) => s.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '* /');

function walk(dir: string, rel = ''): string[] {
  return readdirSync(path.join(dir, rel), {withFileTypes: true}).flatMap((e) => (e.isDirectory() ? walk(dir, path.posix.join(rel, e.name)) : [path.posix.join(rel, e.name)]));
}

// All files the scaffold writes, as {path relative to the studio root → content}.
export function render(plan: Plan, studioRoot: string, notes: string[] = []): Map<string, string> {
  const g = grid(plan);
  const L = layout(plan.slug);
  const fonts = brandFonts(plan, studioRoot, notes);
  const segs = plan.segments;
  const vars: Record<string, string | number> = {
    SLUG: plan.slug,
    PASCAL: L.reelId,
    TITLE: comment(plan.title),
    FPS: plan.fps,
    DURATION: g.duration,
    SECONDS: plan.seconds,
    BEAT: g.beat,
    BPM: plan.bpm,
    BAR: g.bar,
    PAD: g.pad,
    SEG_IDS: segs.map((s) => `'${s.id}'`).join(' | '),
    SEGMENTS: `[\n${segs.map((s, i) => `  {id: '${s.id}', index: ${i + 1}, name: ${JSON.stringify(s.name)}, start: ${s.startFrame}, end: ${s.endFrame}},`).join('\n')}\n]`,
    INTRO_END: plan.intro.endFrame,
    OUTRO_START: plan.outro.startFrame,
    FONT_IMPORTS: fonts.imports,
    FONT_DEFS: fonts.defs,
    BRAND: JSON.stringify({name: plan.brand.name, tagline: plan.brand.tagline ?? ''}),
    COLORS: JSON.stringify(plan.brand.colors, null, 2),
    ACCENTS: `{\n${segs.map((s) => `  ${s.id}: '${s.accent}',`).join('\n')}\n}`,
    W: plan.width,
    H: plan.height,
    // w_/t_ prefixes: a segment id may be a reserved word ("new", "class", …)
    IMPORTS: segs.map((s) => `import * as w_${s.id} from './${s.id}/World';\nimport * as t_${s.id} from './${s.id}/timing';`).join('\n'),
    ENTRIES: segs.map((s) => `  ${s.id}: {World: w_${s.id}.World, EVENTS: t_${s.id}.EVENTS, HERO_FRAME: t_${s.id}.HERO_FRAME},`).join('\n'),
  };
  const files = new Map<string, string>();
  for (const [from, to] of [
    ['src', L.src],
    ['scripts', L.scripts],
  ] as const) {
    for (const rel of walk(path.join(TEMPLATES, from))) {
      const text = readFileSync(path.join(TEMPLATES, from, rel), 'utf8');
      if (rel.includes('__ID__')) {
        for (const s of segs) {
          const v = {...vars, ID: s.id, HERO: Math.round((s.endFrame - s.startFrame) / 2)};
          files.set(`${to}/${fill(rel, v)}`, fill(text, v));
        }
      } else files.set(`${to}/${rel}`, fill(text, vars));
    }
  }
  return files;
}

// ── studio/src/Root.tsx: generated lines between the markers, tagged `mvo:<slug>` (idempotent) ──
const IMPORT_MARK = '<mvo:imports>';
const COMP_MARK = '<mvo:compositions>';
const tagged = (line: string, slug: string) => {
  const t = line.trimEnd();
  return t.endsWith(`// mvo:${slug}`) || t.endsWith(`{/* mvo:${slug} */}`);
};

export function registerInRoot(studioRoot: string, slug: string, on = true): void {
  const file = path.join(studioRoot, 'src/Root.tsx');
  const text = readFileSync(file, 'utf8');
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split(/\r?\n/).filter((l) => !tagged(l, slug));
  if (on) {
    const P = pascal(slug);
    const im = lines.findIndex((l) => l.includes(IMPORT_MARK));
    if (im < 0) throw new Error(`src/Root.tsx has no "${IMPORT_MARK}" marker line`);
    lines.splice(im + 1, 0, `import {Compositions as ${P}Compositions} from './${slug}/Root'; // mvo:${slug}`);
    const cm = lines.findIndex((l) => l.includes(COMP_MARK));
    if (cm < 0) throw new Error(`src/Root.tsx has no "${COMP_MARK}" marker line`);
    lines.splice(cm + 1, 0, `${/^\s*/.exec(lines[cm])![0]}<${P}Compositions />{/* mvo:${slug} */}`);
  }
  const out = lines.join(eol);
  if (out !== text) writeFileSync(file, out);
}

// Is this slug's folder ours (generated) or someone's hand-made template?
const ours = (studioRoot: string, slug: string) => {
  const t = path.join(studioRoot, 'src', slug, 'timing.ts');
  return !existsSync(path.join(studioRoot, 'src', slug)) || (existsSync(t) && readFileSync(t, 'utf8').includes(MARK));
};

export function removeScaffold(studioRoot: string, slug: string): void {
  if (!ours(studioRoot, slug)) throw new Error(`studio/src/${slug} was not generated by motion-orchestrator; refusing to delete it`);
  const L = layout(slug);
  for (const d of [L.src, L.scripts, L.public, L.out]) rmSync(path.join(studioRoot, d), {recursive: true, force: true});
  registerInRoot(studioRoot, slug, false);
}

export type ScaffoldResult = {files: string[]; notes: string[]; still: string; log: string};

// Write everything, register, then prove it: tsc clean, placeholder music masters, a still renders.
export async function scaffold(o: {plan: Plan; studioRoot: string; stillsDir: string; signal?: AbortSignal; onLog?: (l: string) => void}): Promise<ScaffoldResult> {
  const {plan, studioRoot} = o;
  const L = layout(plan.slug);
  const log = (l: string) => o.onLog?.(l);
  if (!ours(studioRoot, plan.slug)) throw new Error(`studio/src/${plan.slug} already exists and was not generated by motion-orchestrator: pick another slug`);
  const root = readFileSync(path.join(studioRoot, 'src/Root.tsx'), 'utf8')
    .split(/\r?\n/)
    .filter((l) => !tagged(l, plan.slug))
    .join('\n');
  for (const id of [L.reelId, L.segCompId]) if (root.includes(`id="${id}"`)) throw new Error(`composition id "${id}" already exists in src/Root.tsx: pick another slug`);

  removeScaffold(studioRoot, plan.slug); // fresh start: the plan is the source of truth
  const notes: string[] = [];
  const files = render(plan, studioRoot, notes);
  for (const [rel, text] of files) {
    const abs = path.join(studioRoot, rel);
    mkdirSync(path.dirname(abs), {recursive: true});
    writeFileSync(abs, text);
  }
  mkdirSync(path.join(studioRoot, L.public), {recursive: true});
  registerInRoot(studioRoot, plan.slug);
  log(`scaffold: wrote ${files.size} files under ${L.src}/ and ${L.scripts}/, registered ${L.reelId} + ${L.segCompId} in src/Root.tsx`);
  for (const n of notes) log(`scaffold: ${n}`);

  const tc = await typecheck(studioRoot, o.signal);
  const mine = tc.errors.filter((e) => e.file.startsWith(`${L.src}/`) || e.file === 'src/Root.tsx');
  if (mine.length) throw new Error(`scaffold does not typecheck:\n${mine.map((e) => e.raw).join('\n')}`);
  const music = await node(studioRoot, `${L.scripts}/music.ts`, [], {signal: o.signal, timeoutMs: 10 * 60_000});
  if (music.code !== 0) throw new Error(`scaffold: placeholder music failed:\n${tail(music.out)}`);
  log(`scaffold: placeholder music ok (${(music.ms / 1000).toFixed(1)} s)`);
  const g = grid(plan);
  const st = await renderStills({studioRoot, slug: plan.slug, compId: L.reelId, props: null, frames: [Math.round(plan.intro.endFrame / 2)], outDir: o.stillsDir, signal: o.signal});
  if (!st.ok) throw new Error(`scaffold: still render failed:\n${st.details}`);
  log(`scaffold: still ok (${g.duration} frames, ${plan.width}×${plan.height}) → ${st.files[0]}`);
  return {files: [...files.keys()], notes, still: st.files[0], log: tail(music.out, 1500)};
}
