import {readFileSync,writeFileSync,statSync,existsSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../..'),file=resolve(root,'out/montage-pro-phone.mp4');
mkdirSync(resolve(root,'evidence'),{recursive:true});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const metadata=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));
const video=metadata.streams.find(s=>s.codec_type==='video'),audio=metadata.streams.find(s=>s.codec_type==='audio');
assert.equal(video.width,1080);assert.equal(video.height,1920);assert.equal(video.r_frame_rate,'60/1');assert.equal(Number(video.nb_frames),9840);
assert.equal(video.codec_name,'h264');assert.equal(video.pix_fmt,'yuv420p');assert.equal(video.color_space,'bt709');
assert.equal(Number(video.duration),164);assert.equal(audio.codec_name,'aac');assert.equal(audio.channels,2);
const decode=spawnSync('ffmpeg',['-v','error','-xerror','-i',file,'-f','null','-'],{encoding:'utf8',maxBuffer:4*1024*1024});
assert.equal(decode.status,0,decode.stderr);
const level=spawnSync('ffmpeg',['-hide_banner','-nostats','-i',file,'-vn','-af','loudnorm=I=-14:TP=-1:LRA=11:print_format=json','-f','null','-'],{encoding:'utf8',maxBuffer:4*1024*1024});
assert.equal(level.status,0,level.stderr);
const measured=JSON.parse(level.stderr.match(/\{\s*"input_i"[\s\S]*?\}/)?.[0]??'null');assert(measured);
assert(Math.abs(Number(measured.input_i)+14)<=1,JSON.stringify(measured));assert(Number(measured.input_tp)<=-1,JSON.stringify(measured));
const onset=spawnSync(process.execPath,['scripts/mpw/check.ts',file],{cwd:resolve(root,'studio'),encoding:'utf8',maxBuffer:4*1024*1024});
writeFileSync(resolve(root,'evidence/phone-master-onsets.log'),onset.stdout+onset.stderr);assert.equal(onset.status,0,onset.stdout+onset.stderr);
const baselinePath=resolve(root,'evidence/desktop-baseline.json');
const baseline=existsSync(baselinePath)?JSON.parse(readFileSync(baselinePath,'utf8').replace(/^\uFEFF/,'')):[];
for(const original of baseline)assert.equal(hash(original.path),original.sha256,`Desktop source changed: ${original.path}`);
const report={testedAt:new Date().toISOString(),passed:true,file:'montage-pro-phone.mp4',bytes:statSync(file).size,sha256:hash(file),video:{width:video.width,height:video.height,fps:60,frames:Number(video.nb_frames),duration:Number(video.duration),codec:video.codec_name,pixelFormat:video.pix_fmt,colorSpace:video.color_space},audio:{codec:audio.codec_name,channels:audio.channels,sampleRate:Number(audio.sample_rate),integratedLUFS:Number(measured.input_i),truePeakDBTP:Number(measured.input_tp),onsets:75},fullDecode:true,desktopFilesUnchanged:baseline.length,scope:'Native portrait render, sampled visual review and browser emulation; no physical-phone or continuous listening acceptance.'};
writeFileSync(resolve(root,'out/montage-pro-phone-qa.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
