// __TITLE__ — brand tokens. GENERATED by motion-orchestrator from plan.brand (do not edit: re-scaffold instead).
__FONT_IMPORTS__
import type {SegId} from './timing';

__FONT_DEFS__

export const BRAND = __BRAND__ as const;

export const C = __COLORS__ as const;

export const ACCENT: Record<SegId, string> = __ACCENTS__;

export const W = __W__;
export const H = __H__;
export const SAFE = 72;
