// __TITLE__ compositions (GENERATED by motion-orchestrator). Registered in studio/src/Root.tsx between the
// <mvo:…> markers, and on their own by entry.ts (a small bundle for fast stills).
import React from 'react';
import {Composition} from 'remotion';
import {Reel} from './Reel';
import {Seg} from './Solo';
import {DURATION, FPS, PAD, SEGMENTS} from './timing';
import {H, W} from './brand';

const SEG_FRAMES = Math.max(...SEGMENTS.map((s) => s.end - s.start)) + 2 * PAD;

export const Compositions: React.FC = () => (
  <>
    <Composition id="__PASCAL__" component={Reel} durationInFrames={DURATION} fps={FPS} width={W} height={H} />
    {/* debug: one segment alone (props {id}); local frame 0 = composition frame PAD */}
    <Composition id="__PASCAL__Seg" component={Seg} durationInFrames={SEG_FRAMES} fps={FPS} width={W} height={H} defaultProps={{id: SEGMENTS[0].id}} />
  </>
);
