// Debug composition (GENERATED by motion-orchestrator): one segment alone; local frame 0 = composition frame PAD.
import React from 'react';
import {AbsoluteFill} from 'remotion';
import {C} from './brand';
import type {SegId} from './timing';
import {SEG_IMPL} from './segments';

export const Seg: React.FC<{id: SegId}> = ({id}) => {
  const impl = SEG_IMPL[id];
  if (!impl) throw new Error(`unknown segment "${id}"`);
  return (
    <AbsoluteFill style={{background: C.bg}}>
      <impl.World />
    </AbsoluteFill>
  );
};
