// __TITLE__ — global layout: the single source of truth for picture AND sound.
// GENERATED by motion-orchestrator from the plan (do not edit: re-scaffold instead).
// Plain TS (no JSX/enums) so `node scripts/__SLUG__/*.ts` can import it.

export const FPS = __FPS__;
export const DURATION = __DURATION__; // __SECONDS__ s
export const BEAT = __BEAT__; // __BPM__ BPM
export const BAR = __BAR__;
export const PAD = __PAD__; // section Sequences start PAD frames early and end PAD frames late (transition overlap)

export type SegId = __SEG_IDS__;
export type SegmentInfo = {id: SegId; index: number; name: string; start: number; end: number};

export const SEGMENTS: SegmentInfo[] = __SEGMENTS__;

export const INTRO = {start: 0, end: __INTRO_END__};
export const OUTRO = {start: __OUTRO_START__, end: DURATION};

export type SectionId = 'intro' | SegId | 'outro';
export type Section = {id: SectionId; index: number; name: string; start: number; end: number};
export const SECTIONS: Section[] = [{id: 'intro', index: 0, name: 'INTRO', ...INTRO}, ...SEGMENTS, {id: 'outro', index: SEGMENTS.length + 1, name: 'OUTRO', ...OUTRO}];

// Every sound-bearing moment of a segment. `f` is LOCAL to its segment (0 = segment start frame).
// impact/hit may also drive the global camera shake (`shake` = px amplitude, ~6–14).
export type WorldEvent = {f: number; kind: 'impact' | 'hit' | 'tick' | 'whoosh' | 'blip'; shake?: number};

export const segById = (id: SegId) => SEGMENTS.find((s) => s.id === id)!;

// Seeded PRNG: the ONLY allowed source of randomness (never Math.random).
export const mulberry32 = (seed: number) => () => {
  seed |= 0;
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
