// Segment registry. GENERATED by motion-orchestrator (segment builders edit only their own folder).
import type React from 'react';
import type {SegId, WorldEvent} from '../timing';
import * as w_voice from './voice/World';
import * as t_voice from './voice/timing';
import * as w_tones from './tones/World';
import * as t_tones from './tones/timing';
import * as w_montage from './montage/World';
import * as t_montage from './montage/timing';
import * as w_editor from './editor/World';
import * as t_editor from './editor/timing';
import * as w_charforge from './charforge/World';
import * as t_charforge from './charforge/timing';
import * as w_forgeatlas from './forgeatlas/World';
import * as t_forgeatlas from './forgeatlas/timing';
import * as w_cake from './cake/World';
import * as t_cake from './cake/timing';
import * as w_educate from './educate/World';
import * as t_educate from './educate/timing';
import * as w_downloader from './downloader/World';
import * as t_downloader from './downloader/timing';
import * as w_macroforge from './macroforge/World';
import * as t_macroforge from './macroforge/timing';
import * as w_reclaim from './reclaim/World';
import * as t_reclaim from './reclaim/timing';
import * as w_orbit from './orbit/World';
import * as t_orbit from './orbit/timing';
import * as w_business from './business/World';
import * as t_business from './business/timing';
import * as w_talent from './talent/World';
import * as t_talent from './talent/timing';
import * as w_marketplace from './marketplace/World';
import * as t_marketplace from './marketplace/timing';
import * as w_retail from './retail/World';
import * as t_retail from './retail/timing';
import * as w_quotes from './quotes/World';
import * as t_quotes from './quotes/timing';
import * as w_workflows from './workflows/World';
import * as t_workflows from './workflows/timing';
import * as w_marketing from './marketing/World';
import * as t_marketing from './marketing/timing';
import * as w_askrepos from './askrepos/World';
import * as t_askrepos from './askrepos/timing';
import * as w_flock from './flock/World';
import * as t_flock from './flock/timing';
import * as w_factory from './factory/World';
import * as t_factory from './factory/timing';
import * as w_games from './games/World';
import * as t_games from './games/timing';

export const SEG_IMPL: Record<SegId, {World: React.FC; EVENTS: WorldEvent[]; HERO_FRAME: number}> = {
  voice: {World: w_voice.World, EVENTS: t_voice.EVENTS, HERO_FRAME: t_voice.HERO_FRAME},
  tones: {World: w_tones.World, EVENTS: t_tones.EVENTS, HERO_FRAME: t_tones.HERO_FRAME},
  montage: {World: w_montage.World, EVENTS: t_montage.EVENTS, HERO_FRAME: t_montage.HERO_FRAME},
  editor: {World: w_editor.World, EVENTS: t_editor.EVENTS, HERO_FRAME: t_editor.HERO_FRAME},
  charforge: {World: w_charforge.World, EVENTS: t_charforge.EVENTS, HERO_FRAME: t_charforge.HERO_FRAME},
  forgeatlas: {World: w_forgeatlas.World, EVENTS: t_forgeatlas.EVENTS, HERO_FRAME: t_forgeatlas.HERO_FRAME},
  cake: {World: w_cake.World, EVENTS: t_cake.EVENTS, HERO_FRAME: t_cake.HERO_FRAME},
  educate: {World: w_educate.World, EVENTS: t_educate.EVENTS, HERO_FRAME: t_educate.HERO_FRAME},
  downloader: {World: w_downloader.World, EVENTS: t_downloader.EVENTS, HERO_FRAME: t_downloader.HERO_FRAME},
  macroforge: {World: w_macroforge.World, EVENTS: t_macroforge.EVENTS, HERO_FRAME: t_macroforge.HERO_FRAME},
  reclaim: {World: w_reclaim.World, EVENTS: t_reclaim.EVENTS, HERO_FRAME: t_reclaim.HERO_FRAME},
  orbit: {World: w_orbit.World, EVENTS: t_orbit.EVENTS, HERO_FRAME: t_orbit.HERO_FRAME},
  business: {World: w_business.World, EVENTS: t_business.EVENTS, HERO_FRAME: t_business.HERO_FRAME},
  talent: {World: w_talent.World, EVENTS: t_talent.EVENTS, HERO_FRAME: t_talent.HERO_FRAME},
  marketplace: {World: w_marketplace.World, EVENTS: t_marketplace.EVENTS, HERO_FRAME: t_marketplace.HERO_FRAME},
  retail: {World: w_retail.World, EVENTS: t_retail.EVENTS, HERO_FRAME: t_retail.HERO_FRAME},
  quotes: {World: w_quotes.World, EVENTS: t_quotes.EVENTS, HERO_FRAME: t_quotes.HERO_FRAME},
  workflows: {World: w_workflows.World, EVENTS: t_workflows.EVENTS, HERO_FRAME: t_workflows.HERO_FRAME},
  marketing: {World: w_marketing.World, EVENTS: t_marketing.EVENTS, HERO_FRAME: t_marketing.HERO_FRAME},
  askrepos: {World: w_askrepos.World, EVENTS: t_askrepos.EVENTS, HERO_FRAME: t_askrepos.HERO_FRAME},
  flock: {World: w_flock.World, EVENTS: t_flock.EVENTS, HERO_FRAME: t_flock.HERO_FRAME},
  factory: {World: w_factory.World, EVENTS: t_factory.EVENTS, HERO_FRAME: t_factory.HERO_FRAME},
  games: {World: w_games.World, EVENTS: t_games.EVENTS, HERO_FRAME: t_games.HERO_FRAME},
};
