// MK Suite - Every idea has a world — brand tokens. GENERATED by motion-orchestrator from plan.brand (do not edit: re-scaffold instead).
import {loadFont as loadSpaceGrotesk} from '@remotion/google-fonts/SpaceGrotesk';
import {loadFont as loadInter} from '@remotion/google-fonts/Inter';
import {loadFont as loadJetBrainsMono} from '@remotion/google-fonts/JetBrainsMono';
import type {SegId} from './timing';

const loadSpaceGroteskFamily = loadSpaceGrotesk('normal', {weights: ["400","500","600","700"], subsets: ['latin']}).fontFamily;
export const FONT = loadSpaceGroteskFamily;
const loadInterFamily = loadInter('normal', {weights: ["400","500","600","700","800","900"], subsets: ['latin']}).fontFamily;
export const BODY = loadInterFamily;
const loadJetBrainsMonoFamily = loadJetBrainsMono('normal', {weights: ["400","500","600","700","800"], subsets: ['latin']}).fontFamily;
export const MONO = loadJetBrainsMonoFamily;

export const BRAND = {"name":"MK Suite","tagline":"One suite. One monthly subscription."} as const;

export const C = {
  "bg": "#10121A",
  "fg": "#F9F5EC",
  "primary": "#EE6045",
  "sub": "#ACAEB9"
} as const;

export const ACCENT: Record<SegId, string> = {
  voice: '#46E7AB',
  tones: '#ED823C',
  montage: '#FF536A',
  editor: '#476EFF',
  charforge: '#C395FF',
  forgeatlas: '#6DC8FA',
  cake: '#ED6A9B',
  educate: '#526CBB',
  downloader: '#43DDF1',
  macroforge: '#FF824B',
  reclaim: '#93AC5B',
  orbit: '#F4B15E',
  business: '#F08F66',
  talent: '#AB8CF0',
  marketplace: '#F4C94C',
  retail: '#2DAF96',
  quotes: '#D7B064',
  workflows: '#A194EF',
  marketing: '#F47352',
  askrepos: '#B4F45E',
  flock: '#C8AD66',
  factory: '#FF9250',
  games: '#EF76FF',
};

export const W = 1920;
export const H = 1080;
export const SAFE = 72;
