// MK Suite - Every idea has a world — global layout: the single source of truth for picture AND sound.
// GENERATED by motion-orchestrator from the plan (do not edit: re-scaffold instead).
// Plain TS (no JSX/enums) so `node scripts/mk-suite-worlds/*.ts` can import it.

export const FPS = 60;
export const DURATION = 5400; // 90 s
export const BEAT = 24; // 150 BPM
export const BAR = 96;
export const PAD = 12; // section Sequences start PAD frames early and end PAD frames late (transition overlap)

export type SegId = 'voice' | 'tones' | 'montage' | 'editor' | 'charforge' | 'forgeatlas' | 'cake' | 'educate' | 'downloader' | 'macroforge' | 'reclaim' | 'orbit' | 'business' | 'talent' | 'marketplace' | 'retail' | 'quotes' | 'workflows' | 'marketing' | 'askrepos' | 'flock' | 'factory' | 'games';
export type SegmentInfo = {id: SegId; index: number; name: string; start: number; end: number};

export const SEGMENTS: SegmentInfo[] = [
  {id: 'voice', index: 1, name: "MK Voice", start: 192, end: 480},
  {id: 'tones', index: 2, name: "MK Tones", start: 480, end: 768},
  {id: 'montage', index: 3, name: "Montage Pro", start: 768, end: 1056},
  {id: 'editor', index: 4, name: "MK Editor", start: 1056, end: 1248},
  {id: 'charforge', index: 5, name: "CharForge Studio", start: 1248, end: 1440},
  {id: 'forgeatlas', index: 6, name: "Forge Atlas", start: 1440, end: 1632},
  {id: 'cake', index: 7, name: "Cake Studio", start: 1632, end: 1824},
  {id: 'educate', index: 8, name: "MK Educate", start: 1824, end: 2112},
  {id: 'downloader', index: 9, name: "MK Downloader", start: 2112, end: 2304},
  {id: 'macroforge', index: 10, name: "MacroForge", start: 2304, end: 2496},
  {id: 'reclaim', index: 11, name: "Reclaim", start: 2496, end: 2688},
  {id: 'orbit', index: 12, name: "Job Engine / Orbit", start: 2688, end: 2880},
  {id: 'business', index: 13, name: "MK Business OS", start: 2880, end: 3168},
  {id: 'talent', index: 14, name: "Talent Atlas", start: 3168, end: 3360},
  {id: 'marketplace', index: 15, name: "MK Marketplace", start: 3360, end: 3552},
  {id: 'retail', index: 16, name: "Retail Ops Hub", start: 3552, end: 3744},
  {id: 'quotes', index: 17, name: "Quotation Builder", start: 3744, end: 3936},
  {id: 'workflows', index: 18, name: "Managed Workflows", start: 3936, end: 4128},
  {id: 'marketing', index: 19, name: "Marketing Automation", start: 4128, end: 4320},
  {id: 'askrepos', index: 20, name: "ask-repos", start: 4320, end: 4512},
  {id: 'flock', index: 21, name: "Flock Operations", start: 4512, end: 4704},
  {id: 'factory', index: 22, name: "MK Factory", start: 4704, end: 4992},
  {id: 'games', index: 23, name: "MK Games", start: 4992, end: 5280},
];

export const INTRO = {start: 0, end: 192};
export const OUTRO = {start: 5280, end: DURATION};

export type SectionId = 'intro' | SegId | 'outro';
export type Section = {id: SectionId; index: number; name: string; start: number; end: number};
export const SECTIONS: Section[] = [{id: 'intro', index: 0, name: 'INTRO', ...INTRO}, ...SEGMENTS, {id: 'outro', index: SEGMENTS.length + 1, name: 'OUTRO', ...OUTRO}];

// Every sound-bearing moment of a segment. `f` is LOCAL to its segment (0 = segment start frame).
// impact/hit may also drive the global camera shake (`shake` = px amplitude, ~6–14).
export type WorldEvent = {f: number; kind: 'impact' | 'hit' | 'tick' | 'whoosh' | 'blip'; shake?: number};

export const segById = (id: SegId) => SEGMENTS.find((s) => s.id === id)!;

// Seeded PRNG: the ONLY allowed source of randomness (never Math.random).
export const mulberry32 = (seed: number) => () => {
  seed |= 0;
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
