// Segment registry. GENERATED by motion-orchestrator (segment builders edit only their own folder).
import type React from 'react';
import type {SegId, WorldEvent} from '../timing';
__IMPORTS__

export const SEG_IMPL: Record<SegId, {World: React.FC; EVENTS: WorldEvent[]; HERO_FRAME: number}> = {
__ENTRIES__
};
