// Stand-alone entry for this video's compositions only (smaller bundle → faster stills). GENERATED by motion-orchestrator.
import {registerRoot} from 'remotion';
import {Compositions} from './Root';

registerRoot(Compositions);
