// Fast stills of this video's compositions: one bundle (src/mk-suite-worlds/entry.ts, this video only), one browser.
// Usage: node scripts/mk-suite-worlds/stills.ts <compositionId> <outDir> <propsJson|-> <frame> [frame...]  → <outDir>/<compositionId>-fNNNNN.png
// GENERATED by motion-orchestrator (used by the stills gate; read-only for builders).
import path from 'node:path';
import {bundle} from '@remotion/bundler';
import {openBrowser, renderStill, selectComposition} from '@remotion/renderer';

const [id, outDir, props, ...rest] = process.argv.slice(2);
const frames = rest.map(Number);
if (!id || !outDir || !props || !frames.length || frames.some((f) => !Number.isInteger(f) || f < 0)) {
  console.error('usage: node scripts/mk-suite-worlds/stills.ts <compositionId> <outDir> <propsJson|-> <frame> [frame...]');
  process.exit(1);
}
const inputProps = props === '-' ? {} : (JSON.parse(props) as Record<string, unknown>);
const root = path.resolve(import.meta.dirname, '../..');
const serveUrl = await bundle({entryPoint: path.join(root, 'src/mk-suite-worlds/entry.ts'), publicDir: path.join(root, 'public')});
const browser = await openBrowser('chrome', {chromiumOptions: {gl: 'angle'}});
try {
  const composition = await selectComposition({serveUrl, id, puppeteerInstance: browser, inputProps});
  for (const frame of frames) {
    if (frame >= composition.durationInFrames) throw new Error(`frame ${frame} is outside ${id} (0..${composition.durationInFrames - 1})`);
    const output = path.resolve(outDir, `${id}-f${String(frame).padStart(5, '0')}.png`);
    await renderStill({serveUrl, composition, frame, output, inputProps, puppeteerInstance: browser, overwrite: true, chromiumOptions: {gl: 'angle'}});
    console.log(output);
  }
} finally {
  await browser.close({silent: true});
}
