// Contract between the master music script and each segment's sound module (scripts/mk-suite-workflows/segments/<id>.ts).
// A segment module default-exports `render(ctx)` and writes its sound into ctx.L/R (dry) and ctx.sendL/R (reverb send).
// Write roughly within [at(-PAD), at(length + PAD)]; quiet tails may run up to ~0.5 s past the segment end.
// Level target inside the segment's range: peaks around -6 dBFS, about -16 LUFS (stage.ts does this for you).
// The master matches segments to each other. GENERATED by motion-orchestrator (read-only for builders).

export type SynthCtx = {
  SR: number; // 44100
  L: Float64Array; // dry bus, whole track
  R: Float64Array;
  sendL: Float64Array; // reverb send bus, whole track
  sendR: Float64Array;
  length: number; // segment length in frames
  at: (localFrame: number) => number; // sample index for a segment-local frame (0 = segment start); may be fractional
};

export type SegmentSound = (ctx: SynthCtx) => void;
